# Inverse Transform/ Inverse  Encoding/ Decoding categorical variables:

`Inverse encoding`, also known as inverse transform or decoding categorical variables, is a 
technique used in data preprocessing to convert encoded categorical variables back to their
 original form. This is often necessary after applying encoding techniques like one-hot encoding, 
 label encoding, or ordinal encoding to prepare the data for machine learning models.

` Types of Inverse Encoding:`
1. `Inverse One-Hot Encoding:` This technique is used to reverse the one-hot encoding process, where each category is represented as a binary vector. The inverse process involves identifying which category corresponds to the binary vector and converting it back to its original categorical form.

2.` Inverse Label Encoding:` This technique is used to reverse the label encoding process, where each category is assigned a unique integer. The inverse process involves mapping the integers back to their corresponding categories.

3. `Inverse Ordinal Encoding: `This technique is used to reverse the ordinal encoding process, where categories are assigned integer values based on their order. The inverse process involves mapping the integer values back to their original categories.

4. `Inverse Binary Encoding:` This technique is used to reverse the binary encoding process, where categories are represented as binary digits. The inverse process involves converting the binary digits back to their original categorical form.

In [53]:
# import libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler, Normalizer,OrdinalEncoder

In [54]:
# load the 'titanic' dataset:
df = sns.load_dataset('titanic')
# display the first 5 rows of the dataset:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [55]:
# dont show the warnings:
import warnings
warnings.filterwarnings('ignore')


# impute the missing values fro age, deck , embarked,and embark_town:
df['age'].fillna(df['age'].mean(), inplace=True)

df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df['embark_town'].fillna(df['embark_town'].mode()[0], inplace=True)

# drop the 'deck' column:
df.drop('deck', axis=1, inplace=True)

In [56]:
# encoding all categorical variables and object variables:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_class = LabelEncoder()
le_embarked = LabelEncoder()
le_who = LabelEncoder()
le_adult_male = LabelEncoder()
le_embark_town = LabelEncoder()
le_alive = LabelEncoder()
le_alone = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['class'] = le_class.fit_transform(df['class'])
df['embarked'] = le_embarked.fit_transform(df['embarked'])
df['who'] = le_who.fit_transform(df['who'])
df['adult_male'] = le_adult_male.fit_transform(df['adult_male'])
df['embark_town'] = le_embark_town.fit_transform(df['embark_town'])
df['alive'] = le_alive.fit_transform(df['alive'])
df['alone'] = le_alone.fit_transform(df['alone'])
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,1,22.0,1,0,7.2500,2,2,1,1,2,0,0
1,1,1,0,38.0,1,0,71.2833,0,0,2,0,0,1,0
2,1,3,0,26.0,0,0,7.9250,2,2,2,0,2,1,1
3,1,1,0,35.0,1,0,53.1000,2,0,2,0,2,1,0
4,0,3,1,35.0,0,0,8.0500,2,2,1,1,2,0,1

In [57]:
# inverse transform  the data:
df['sex'] = le_sex.inverse_transform(df['sex'])
df['class'] = le_class.inverse_transform(df['class'])
df['embarked'] = le_embarked.inverse_transform(df['embarked'])
df['who'] = le_who.inverse_transform(df['who'])
df['adult_male'] = le_adult_male.inverse_transform(df['adult_male'])
df['embark_town'] = le_embark_town.inverse_transform(df['embark_town'])
df['alive'] = le_alive.inverse_transform(df['alive'])
df['alone'] = le_alone.inverse_transform(df['alone'])

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True

---