<div style="background-color:#FAF3F3; padding: 20px; border-radius: 10px; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1); border:2px solid #E57373; margin-top: 20px;">
    <h1 style="font-size:28px; font-family:Georgia, serif; color:#D32F2F; text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">
        Exploratory Data Analysis and Machine Learning on Tunnel Boring Machine (TBM)
    </h1>
</div>

<div style="background-color:#E6F9E6; padding: 20px; border-radius: 10px; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1); border:2px solid #66C2A5; margin-top: 20px;">
    <h1 style="font-size:24px; font-family:Georgia, serif; color:#4A90E2; text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">
        About Author
    </h1>
    <div style="text-align:center;">
        <a href="https://misbah.devsil.com/">
            <img src="https://misbah.devsil.com/assets/images/picture%20misbah.png" style="width: 20%; border-radius: 50%;" alt="Misbah Khattak">
        </a>
    </div>
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333; text-align:center;">Mr. Misbah Khattak</h2>
    <p style="font-size:16px; font-family:Georgia, serif; line-height: 1.5em; text-align:center; color:#333;">
        <em>Data Scientist / AI Engineer</em><br>
        BS Computer Science
    </p>
    <div style="text-align:center; margin-top: 10px;">
        <a href="https://www.linkedin.com/mynetwork/grow/">
            <img width="50" height="50" src="https://img.icons8.com/color/48/linkedin.png" alt="linkedin">
        </a>
        <a href="https://github.com/misbahkhattak718-pixel?tab=repositories">
            <img width="50" height="50" src="https://img.icons8.com/ios-glyphs/50/github.png" alt="github">
        </a>
        <a href="https://www.kaggle.com/misbahkhattak123">
            <img width="50" height="50" src="https://img.icons8.com/clouds/100/kaggle.png" alt="kaggle">
        </a>
    </div>
    <div style="text-align:center; margin-top: 20px;">
        <a href="https://misbah.devsil.com/" style="font-size:18px; font-family:Georgia, serif; color:#4A90E2; text-decoration:none; border:2px solid #4A90E2; padding: 5px 15px; border-radius: 5px;">
            Portfolio Site
        </a>
    </div>
</div>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Table of Contents</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: #f4f4f4; /* Light background color */
            color: #333; /* Dark text color */
            padding: 20px;
        }
        h2 {
            color: #007BFF; /* Header color */
            border-bottom: 2px solid #007BFF; /* Underline for the header */
            padding-bottom: 10px;
        }
        ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }
        li {
            margin: 0.5em 0;
            padding: 10px;
            border-left: 3px solid #007BFF; /* Left border for list items */
            background-color: #ffffff; /* White background for list items */
            transition: background-color 0.3s; /* Smooth transition for hover effect */
        }
        li:hover {
            background-color: #e9ecef; /* Light gray on hover */
        }
        li strong {
            color: #0056b3; /* Darker color for strong text */
        }
    </style>
</head>
<body>
    <h2>Table of Contents</h2>
    <ul>
        <li><strong>1. Introduction</strong>
            <ul>
                <li>1.1 Project Description</li>
                <li>1.2 Data Description</li>
                <li>1.3 Objectives</li>
            </ul>
        </li>
        <li><strong>2. Exploratory Data Analysis</strong>
            <ul>
                <li>2.1 Overview of Dataset</li>
                <li>2.2 Basic Statistics</li>
                <li>2.3 Data Visualization</li>
                <li>2.4 Correlation Analysis</li>
                <li>2.5 Category Analysis</li>
                <li>2.6 Time Series Analysis</li>
                <li>2.7 Outlier Detection</li>
                <li>2.8 Visualizations for Each Column</li>
                <li>2.9 Insights and Recommendations</li>
            </ul>
        </li>
        <li><strong>3. Modeling</strong>
            <ul>
                <li>3.1 Data Preprocessing</li>
                <li>3.2 Weak Supervision</li>
                <li><strong>3.3 Comparative Analysis</strong>
                    <ul>
                        <li>3.3.1 Random Forest</li>
                        <li>3.3.2 Support Vector Machines (SVM)</li>
                        <li>3.3.3 Logistic Regression</li>
                    </ul>
                </li>
                <li>3.4 WEKA Classification</li>
            </ul>
        </li>
        <li><strong>4. Conclusion</strong>

<div style="background-color:#D0E6F3; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1); border:2px solid #66C2A5; margin-top: 15px;">
    <h1 style="font-size:24px; font-family:Georgia, serif; color:#000000; text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">
        1. Introduction
    </h1>
</div>

---



## Project Description

### Introduction
This project revolves around analyzing the operational data from a tunneling machine used in construction. The data consists of various parameters recorded during drilling operations, such as stroke numbers, times, torque, and energy consumption. The goal is to assess the machine's efficiency, identify trends, and make recommendations for optimizing operations.

### Assumptions
In approaching this project, several assumptions were made:
- The data provided is accurate and represents typical operational conditions for the tunneling machine.
- External factors such as weather or geological changes are not considered, as the focus remains on the machine's performance.
- Sufficiently large datasets are available to draw meaningful conclusions.

## Methodology
The methodology applied in this project involves several steps:

1. **Data Collection**: Gather all relevant operational data from the tunneling machine, ensuring it's formatted correctly for analysis.
   
2. **Data Cleaning**: Identify and rectify any inconsistencies or errors in the data to ensure reliability in the findings.

3. **Exploratory Data Analysis (EDA)**:
   - **Statistical Analysis**: Calculate key metrics such as average stroke times, energy usage, and other performance indicators.
   - **Visualization**: Create graphs and charts to visually interpret trends and correlations within the data.
   - **Insights Extraction**: Identify patterns that could indicate inefficiencies or exceptional performance.
   
4. **Modeling**: Develop predictive models to estimate future performance based on historical data, utilizing techniques like regression analysis or machine learning algorithms.

5. **Recommendations**: Based on the analysis, offer actionable insights aimed at improving the efficiency of the tunneling operations.

## Data Description
The dataset comprises the following parameters:


| **Parameter**                   | **Description**                                           |
|----------------------------------|----------------------------------------------------------|
| **Stroke Number**                | An identifier for each drilling operation.               |
| **Date and Advance Time**        | The date of the operation and the duration it took.     |
| **Excavation per Stroke**        | The amount of material excavated with each drill stroke. |
| **Torque**                       | Measure of the rotational force exerted by the machine.  |
| **Thrust**                       | Measure of the linear force exerted by the machine.      |
| **Boring Energy**                | Energy consumed during the drilling process.             |
| **RPM (Revolutions per Minute)** | The speed of the drill.                                  |
| **Speed**                        | The operational speed of the machine.                    |
| **Gripper Pressure**             | The pressure applied by the grippers.                    |
| **Other Parameters**             | Include total revolutions, various pressures, and quality measures. |

This table provides an organized view of each parameter, making it easy to understand their meanings and significance in the context of the project.



## Objectives
The main objectives of the project are:

1. **Efficiency Assessment**: Evaluate the efficiency of the tunneling machine based on operational data to identify areas for improvement.

2. **Trend Analysis**: Understand trends over time to gauge whether performance improves, declines, or remains stable.

3. **Parameter Correlation**: Analyze how different operational parameters (e.g., torque, speed, and thrust) may affect overall performance.

4. **Actionable Insights**: Provide stakeholders with clear, actionable recommendations that can enhance the productivity and efficiency of future tunneling projects.

---

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        Import Libraries
    </h2>
</div>

In [1]:
# import libraries:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats
import plotly.express as px

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        loading dataset
    </h2>
</div>

In [29]:
# loading dataset:
df = pd.read_excel("../../Practice/01_python_first/TBM data Exam.xlsx")

# used the code which is show the name of the columns in the dataset:
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

<div style="background-color:#D0E6F3; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.1); border:2px solid #66C2A5; margin-top: 15px;">
    <h1 style="font-size:24px; font-family:Georgia, serif; color:#000000; text-align: center; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);">
    2.  Exploratory Data Analysis
    </h1>
</div>

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
   2.1 Overview of Dataset
    </h2>
</div>

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        - Show the first few rows of the datafram
    </h2>
</div>

In [28]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Sr,Stroke No.,Date,Advance Time,Excavation per Stroke,Boring Energy,RPM,Torque,Thrust Force,Speed,Gripper Pressure,Total Revolution,Front Shield Pressure LHS,Front Shield Pressure rHS,Q-Value,Q-Value based,Penetration
1,NaN,NaN,NaN,min,(m),(N/mm2),NaN,(KN-m),(KN),(mm/min),(Bar),NaN,(Bar),(Bar),NJC,Boring Energy,(mm/rpm)
2,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
3,2,3813,2016-01-23 00:00:00,78,1.559,9.9,2.3,800,3224,20,242,179,60,62,4,4,8.6
4,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        - Show the last few rows of the datafram
    </h2>
</div>

In [18]:
df.tail()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
1469,129,4912,2016-11-18 00:00:00,33,1.52,8.3,3.2,1100,2783,46,199,106,39,31,4,5,14.5
1470,130,4913,2016-11-18 00:00:00,27,1.23,8.4,3.1,1100,2601,44,189,84,37,31,4,5,14.2
1471,131,4914,2016-11-18 00:00:00,34,1.52,7.4,3.4,900,3040,45,191,116,45,35,4,5,13.3
1472,132,4915,2016-11-18 00:00:00,5,0.15,7.9,3.4,600,2546,28,186,17,81,79,4,5,8.3
1473,133,4916,2016-11-18 00:00:00,24,1.08,8.8,3.5,1000,3465,43,188,84,49,57,4,5,12.2

In [19]:
# print the shape of the dataset:
print("Shape of the dataset:", df.shape)

# print the columns and rows count :
print(f"Number of columns: {df.shape[1]}")
print(f"Number of rows: {df.shape[0]}")

Shape of the dataset: (1474, 17)
Number of columns: 17
Number of rows: 1474

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1474 entries, 0 to 1473
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1473 non-null   object
 1   Unnamed: 1   1473 non-null   object
 2   Unnamed: 2   1473 non-null   object
 3   Unnamed: 3   1474 non-null   object
 4   Unnamed: 4   1474 non-null   object
 5   Unnamed: 5   1474 non-null   object
 6   Unnamed: 6   1473 non-null   object
 7   Unnamed: 7   1474 non-null   object
 8   Unnamed: 8   1474 non-null   object
 9   Unnamed: 9   1474 non-null   object
 10  Unnamed: 10  1474 non-null   object
 11  Unnamed: 11  1473 non-null   object
 12  Unnamed: 12  1474 non-null   object
 13  Unnamed: 13  1474 non-null   object
 14  Unnamed: 14  1474 non-null   object
 15  Unnamed: 15  1474 non-null   object
 16  Unnamed: 16  1474 non-null   object
dtypes: object(17)
memory usage: 195.9+ KB

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        - Check the Datatypes:
    </h2>
</div>

In [22]:
# Check the Datatypes:
df.dtypes

Unnamed: 0     object
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
Unnamed: 10    object
Unnamed: 11    object
Unnamed: 12    object
Unnamed: 13    object
Unnamed: 14    object
Unnamed: 15    object
Unnamed: 16    object
dtype: object

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        - Summary of statistics:
    </h2>
</div>

In [40]:
# Summary of statistics:
df.describe()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
count,1473,1473,1473,1474,1474.00,1474.0,1473.0,1474,1474,1474,1474,1473,1474,1474,1474,1474,1474.0
unique,213,1240,220,73,479.00,259.0,35.0,38,1205,46,65,147,70,80,4,6,87.0
top,1,3970,2016-11-05 00:00:00,26,1.23,11.4,3.8,1200,3224,44,189,109,31,32,4,4,12.9
freq,11,2,18,153,52.00,30.0,147.0,186,4,124,233,56,67,66,1075,739,55.0

<div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
     - Check the uniqueness:
    </h2>
</div>

In [32]:
# Check the uniqueness values in each column:
print(f"Unique values in each column:\n{df.nunique()}")

Unique values in each column:
Unnamed: 0      213
Unnamed: 1     1240
Unnamed: 2      220
Unnamed: 3       73
Unnamed: 4      479
Unnamed: 5      259
Unnamed: 6       35
Unnamed: 7       38
Unnamed: 8     1205
Unnamed: 9       46
Unnamed: 10      65
Unnamed: 11     147
Unnamed: 12      70
Unnamed: 13      80
Unnamed: 14       4
Unnamed: 15       6
Unnamed: 16      87
dtype: int64

  <div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
     - Rename the columns:
    </h2>
</div>

In [41]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Sr,Stroke No.,Date,Advance Time,Excavation per Stroke,Boring Energy,RPM,Torque,Thrust Force,Speed,Gripper Pressure,Total Revolution,Front Shield Pressure LHS,Front Shield Pressure rHS,Q-Value,Q-Value based,Penetration
1,NaN,NaN,NaN,min,(m),(N/mm2),NaN,(KN-m),(KN),(mm/min),(Bar),NaN,(Bar),(Bar),NJC,Boring Energy,(mm/rpm)
2,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
3,2,3813,2016-01-23 00:00:00,78,1.559,9.9,2.3,800,3224,20,242,179,60,62,4,4,8.6
4,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5

In [42]:
# Changing the column names to more descriptive ones:
df.rename(
    columns={
        "Unnamed: 0": "Sr",
        "Unnamed: 1": "Stroke .No",
        "Unnamed: 2": "Data",
        "Unnamed: 3": "Advance Time (min)",
        "Unnamed: 4": "Excavation per Stroke (m)",
        "Unnamed: 5": "Boring Energy (N/mm2)",
        "Unnamed: 6": "RPM",
        "Unnamed: 7": "Torque (kN-m)",
        "Unnamed: 8": "Thrust Force (kN)",
        "Unnamed: 9": "Speed",
        "Unnamed: 10": "Gripper Pressure (Bar)",
        "Unnamed: 11": "Total Revolution",
        "Unnamed: 12": "Front Shield Pressure LHS (Bar)",
        "Unnamed: 13": "Front Shield Pressure rHS (Bar)",
        "Unnamed: 14": "Q-Value (NJC)",
        "Unnamed: 15": "Q-Value based Boring Energy",
        "Unnamed: 16": "Penetration (mm/rpm)",
    },
    inplace=True,
)

In [43]:
df.head()

,Sr,Stroke .No,Data,Advance Time (min),Excavation per Stroke (m),Boring Energy (N/mm2),RPM,Torque (kN-m),Thrust Force (kN),Speed,Gripper Pressure (Bar),Total Revolution,Front Shield Pressure LHS (Bar),Front Shield Pressure rHS (Bar),Q-Value (NJC),Q-Value based Boring Energy,Penetration (mm/rpm)
0,Sr,Stroke No.,Date,Advance Time,Excavation per Stroke,Boring Energy,RPM,Torque,Thrust Force,Speed,Gripper Pressure,Total Revolution,Front Shield Pressure LHS,Front Shield Pressure rHS,Q-Value,Q-Value based,Penetration
1,NaN,NaN,NaN,min,(m),(N/mm2),NaN,(KN-m),(KN),(mm/min),(Bar),NaN,(Bar),(Bar),NJC,Boring Energy,(mm/rpm)
2,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
3,2,3813,2016-01-23 00:00:00,78,1.559,9.9,2.3,800,3224,20,242,179,60,62,4,4,8.6
4,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5

  <div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
        - Check the missing values:
    </h2>
</div>

In [44]:
# Check the missing values:
print(f"Missing values in each column:\n{df.isnull().sum().sort_values(ascending=False)}")

Missing values in each column:
Sr                                 1
Stroke .No                         1
Data                               1
RPM                                1
Total Revolution                   1
Excavation per Stroke (m)          0
Boring Energy (N/mm2)              0
Torque (kN-m)                      0
Advance Time (min)                 0
Thrust Force (kN)                  0
Speed                              0
Gripper Pressure (Bar)             0
Front Shield Pressure LHS (Bar)    0
Front Shield Pressure rHS (Bar)    0
Q-Value (NJC)                      0
Q-Value based Boring Energy        0
Penetration (mm/rpm)               0
dtype: int64

In [45]:
# impute the missing values:
# For numerical columns, we can use the mean or median to fill missing values.
numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    df[col].fillna(df[col].mean(), inplace=True)

In [48]:
# don't show the warnings

import warnings
warnings.filterwarnings("ignore")


# for categorical columns, we can use the mode to fill missing values.
categorical_cols = df.select_dtypes(include=["object"]).columns
for col in categorical_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [49]:
df.isnull().sum()

Sr                                 0
Stroke .No                         0
Data                               0
Advance Time (min)                 0
Excavation per Stroke (m)          0
Boring Energy (N/mm2)              0
RPM                                0
Torque (kN-m)                      0
Thrust Force (kN)                  0
Speed                              0
Gripper Pressure (Bar)             0
Total Revolution                   0
Front Shield Pressure LHS (Bar)    0
Front Shield Pressure rHS (Bar)    0
Q-Value (NJC)                      0
Q-Value based Boring Energy        0
Penetration (mm/rpm)               0
dtype: int64

---

  <div style="background-color:#E6F2FF; padding: 10px; border-radius: 8px; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1); border:1px solid #66C2A5; margin-top: 10px; margin-left: 20px;">
    <h2 style="font-size:20px; font-family:Georgia, serif; color:#333333; text-align: left; margin: 0;">
     2.2 Basic Statistics
    </h2>
</div>

In [50]:
df.head()

,Sr,Stroke .No,Data,Advance Time (min),Excavation per Stroke (m),Boring Energy (N/mm2),RPM,Torque (kN-m),Thrust Force (kN),Speed,Gripper Pressure (Bar),Total Revolution,Front Shield Pressure LHS (Bar),Front Shield Pressure rHS (Bar),Q-Value (NJC),Q-Value based Boring Energy,Penetration (mm/rpm)
0,Sr,Stroke No.,Date,Advance Time,Excavation per Stroke,Boring Energy,RPM,Torque,Thrust Force,Speed,Gripper Pressure,Total Revolution,Front Shield Pressure LHS,Front Shield Pressure rHS,Q-Value,Q-Value based,Penetration
1,1,3812,2016-11-05 00:00:00,min,(m),(N/mm2),3.8,(KN-m),(KN),(mm/min),(Bar),109,(Bar),(Bar),NJC,Boring Energy,(mm/rpm)
2,1,3812,2016-01-23 00:00:00,16,1.612,1.3,2.3,500,3600,101,253,37,80,58,4,5,44.5
3,2,3813,2016-01-23 00:00:00,78,1.559,9.9,2.3,800,3224,20,242,179,60,62,4,4,8.6
4,3,3814,2016-01-23 00:00:00,43,0.901,9.3,2,900,2895,21,245,86,69,69,4,5,10.5

In [54]:
# basic statistics of the dataset:
df.describe().T

                                  count unique                  top   freq
Sr                                 1474    213                    1     12
Stroke .No                         1474   1240                 3812      3
Data                               1474    220  2016-11-05 00:00:00     19
Advance Time (min)                 1474     73                   26    153
Excavation per Stroke (m)        1474.0  479.0                 1.23   52.0
Boring Energy (N/mm2)            1474.0  259.0                 11.4   30.0
RPM                              1474.0   35.0                  3.8  148.0
Torque (kN-m)                      1474     38                 1200    186
Thrust Force (kN)                  1474   1205                 3224      4
Speed                              1474     46                   44    124
Gripper Pressure (Bar)             1474     65                  189    233
Total Revolution                   1474    147                  109     57
Front Shield Pressure LHS (Bar)    1474     70                   31     67
Front Shield Pressure rHS (Bar)    1474     80                   32     66
Q-Value (NJC)                      1474      4                    4   1075
Q-Value based Boring Energy        1474      6                    4    739
Penetration (mm/rpm)             1474.0   87.0                 12.9   55.0